name: Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Docker Build & Push Action
      uses: docker/build-push-action@v5
      with:
        context: .
        file: docker/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/ietf-tools/wiki:2.0.${{ github.run_number }}
          ghcr.io/ietf-tools/wiki:latest

    - name: Package and Push Chart
      env:
        VERSION: 2.0.${{ github.run_number }}
      run: |
        echo "Setting version ${{ env.VERSION }}..."
        sed -i -r -e "s|^version: .*$|version: '${{ env.VERSION }}'|" -e "s|^appVersion: .*$|appVersion: '${{ env.VERSION }}'|" helm/Chart.yaml
        helm plugin install https://github.com/chartmuseum/helm-push.git
        helm repo add chartmuseum https://charts.ietf.org
        helm cm-push --version="${{ env.VERSION }}" --username="${{ secrets.HELM_REPO_USERNAME }}" --password="${{ secrets.HELM_REPO_PASSWORD }}" helm/ chartmuseum
        helm repo remove chartmuseum